services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"
  app:
    image: app
    network_mode: "host"
    environment:
      - HOST=sandbox-iosxr-1.cisco.com
      - USR=admin
      - PASSWD=C1sco12345
